<?php

/**
 * Klimaatadaptieve maatregelen volgens Bijlage E (bron: overzicht_aspecten_maatregelen_bijlage_E.xlsx).
 * Velden 'investering_*' en 'waterberging' ondersteunen filtering en rekenregels uit het Excel-onderdeel "In te vullen gegevens".
 */
return [
    'risico_opties' => [
        'hittestress' => 'Hittestress',
        'wateroverlast' => 'Wateroverlast',
        'droogte' => 'Droogte',
        'overstromingsgevaar' => 'Overstromingsgevaar',
    ],

    /*
    |--------------------------------------------------------------------------
    | Maatregelen
    |--------------------------------------------------------------------------
    | niveaus: subset van gebied, gebouw, beide (beide = gebouw- én gebiedsniveau)
    | investering_eenheid: stuk | m2 | project | onbekend
    | investering_min/max: euro; null = onbekend / niet van toepassing op filter
    | waterberging: effect in m³ per m² dak/oppervlak of per boom voor berekeningen
    | min_oppervlak_pct_verhard: voor regen/wadi — ondergrens % van verhard oppervlak (afgekoppeld ≈ invoer verhard)
    */
    'maatregelen' => [
        [
            'id' => 'droogtebestendige-bomen',
            'naam' => 'Droogtebestendige bomen',
            'niveaus' => ['gebied'],
            'risicos' => ['droogte', 'wateroverlast'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 350,
            'investering_max' => 1250,
            'investering_tekst' => '€350–750 jonge boom; €1.250 volwassen boom',
            'onderhoud_jaar' => '€15 / 2× per jaar / €/boom/jaar',
            'effect_tekst' => '0,2–0,4 m³ waterberging per volwassen boom',
            'technisch' => 'Volgroeide boom 1e grootte: 16 m² bovengrondse groeiruimte',
            'waterberging' => ['soort' => 'per_boom', 'min_m3' => 0.2, 'max_m3' => 0.4],
        ],
        [
            'id' => 'straatbomen-bomenlanen',
            'naam' => 'Straatbomen / bomenlanen',
            'niveaus' => ['gebied'],
            'risicos' => ['hittestress', 'wateroverlast'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 350,
            'investering_max' => 1250,
            'investering_tekst' => '€350–750 jonge boom; €1.250 volwassen boom',
            'onderhoud_jaar' => '€15 / 2× per jaar / €/boom/jaar',
            'effect_tekst' => '10 °C gevoelstemperatuurdaling; 0,2–0,4 m³ waterberging per volwassen boom',
            'technisch' => 'Volgroeide boom 1e grootte: 16 m² bovengrondse groeiruimte',
            'waterberging' => ['soort' => 'per_boom', 'min_m3' => 0.2, 'max_m3' => 0.4],
        ],
        [
            'id' => 'stadsbos',
            'naam' => 'Stadsbos / klein stadsbos',
            'niveaus' => ['gebied'],
            'risicos' => ['hittestress', 'wateroverlast'],
            'investering_eenheid' => 'project',
            'investering_min' => 18000,
            'investering_max' => 18000,
            'investering_tekst' => '€18.000 totaal',
            'onderhoud_jaar' => '€15 / 2× per jaar / €/boom/jaar',
            'effect_tekst' => '0,2–0,4 m³ waterberging per volwassen boom',
            'technisch' => 'Minimaal 200–250 m²; minimaal 4 m breed',
            'waterberging' => ['soort' => 'per_boom', 'min_m3' => 0.2, 'max_m3' => 0.4],
            'min_oppervlak_gebied_m2' => 200,
        ],
        [
            'id' => 'waterdoorlatendheid-vegetatie',
            'naam' => 'Verhoogde waterdoorlatendheid bodem door vegetatie',
            'niveaus' => ['beide'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 2,
            'investering_max' => 5,
            'investering_tekst' => '€2–5 lage/middelhoge kruidensoorten',
            'onderhoud_jaar' => '€2–5 / gemiddeld 2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,0005 m³ waterberging per m²',
            'technisch' => 'Geen harde minimale eis; struik circa 1 m² groeiruimte',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.0005, 'max_m3' => 0.0005],
            'gebied_oppervlak_min_m2' => 1,
        ],
        [
            'id' => 'vegetatie-lokaal-klimaat',
            'naam' => 'Het planten van geschikte lage en hoge vegetatie voor het lokale klimaat',
            'niveaus' => ['beide'],
            'risicos' => ['droogte'],
            'investering_eenheid' => 'm2',
            'investering_min' => 2,
            'investering_max' => 35,
            'investering_tekst' => '€25–35 struiken; €2–5 lage/middelhoge kruidensoorten',
            'onderhoud_jaar' => '€2–20 / gemiddeld 2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,0005 m³ waterberging per m²',
            'technisch' => 'Geen harde minimale eis; struik circa 1 m² groeiruimte',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.0005, 'max_m3' => 0.0005],
            'gebied_oppervlak_min_m2' => 1,
        ],
        [
            'id' => 'tegels-eruit-groen-erin',
            'naam' => 'Tegels eruit, groen erin',
            'niveaus' => ['beide'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 2,
            'investering_max' => 5,
            'investering_tekst' => '€2–5 lage/middelhoge kruidensoorten',
            'onderhoud_jaar' => '€2–5 / gemiddeld 2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,0005 m³ waterberging per m²',
            'technisch' => 'Geen harde minimale eis; struik circa 1 m² groeiruimte',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.0005, 'max_m3' => 0.0005],
            'gebied_oppervlak_min_m2' => 1,
        ],
        [
            'id' => 'groen-blauwe-daken',
            'naam' => 'Groen-blauwe daken / retentiedaken',
            'niveaus' => ['gebouw'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 100,
            'investering_max' => 100,
            'investering_tekst' => '€100 / m²',
            'onderhoud_jaar' => '€2 / 1–3× per jaar / €/m²/jaar',
            'effect_tekst' => '0,07–0,15 m³ waterberging per m²',
            'technisch' => 'Geen harde minimale eis',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.07, 'max_m3' => 0.15],
        ],
        [
            'id' => 'sedumdak',
            'naam' => 'Sedumdak',
            'niveaus' => ['gebouw'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 40,
            'investering_max' => 40,
            'investering_tekst' => '€40 / m²',
            'onderhoud_jaar' => '€1 / zie frequentie in bron / €/m²/jaar',
            'effect_tekst' => '0,015–0,024 m³ waterberging per m²',
            'technisch' => 'Groendak met sedumvegetatie; geschikt voor vlakke daken met voldoende draagkracht.',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.015, 'max_m3' => 0.024],
        ],
        [
            'id' => 'regenwaterton',
            'naam' => 'Regenwaterton',
            'niveaus' => ['gebouw'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 130,
            'investering_max' => 190,
            'investering_tekst' => '€130–190 / stuk',
            'onderhoud_jaar' => 'Geen onderhoudskosten',
            'effect_tekst' => '0,10–0,30 m³ waterberging per stuk',
            'technisch' => 'Regenwater opvangen vanaf dakafvoer; capaciteit afhankelijk van tonvolume.',
            'waterberging' => ['soort' => 'per_stuk', 'min_m3' => 0.10, 'max_m3' => 0.30],
        ],
        [
            'id' => 'waterberging-vijvers',
            'naam' => 'Waterberging / waterbuffers / vijvers rondom gebouw',
            'niveaus' => ['gebied'],
            'risicos' => ['wateroverlast', 'overstromingsgevaar'],
            'investering_eenheid' => 'm2',
            'investering_min' => 15,
            'investering_max' => 60,
            'investering_tekst' => '€15–60 / m²',
            'onderhoud_jaar' => '€1 / 1–2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,3 m³ waterberging per m²',
            'technisch' => 'Geen harde minimale eis; realistische ondergrens circa 5 m²',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.3, 'max_m3' => 0.3],
        ],
        [
            'id' => 'regentuinen',
            'naam' => 'Regentuinen',
            'niveaus' => ['gebied'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 125,
            'investering_max' => 130,
            'investering_tekst' => '€125–130 / m²',
            'onderhoud_jaar' => '€5–15 / 2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,3–0,5 m³ waterberging per m²',
            'technisch' => 'Oppervlakte minimaal 5–10% van afgekoppeld oppervlak',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.3, 'max_m3' => 0.5],
            'min_oppervlak_pct_verhard' => ['min' => 0.05, 'max' => 0.10],
        ],
        [
            'id' => 'wadis',
            'naam' => 'Wadi’s',
            'niveaus' => ['gebied'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 20,
            'investering_max' => 75,
            'investering_tekst' => '€20–75 / m²',
            'onderhoud_jaar' => '€0,40–7,50 / 2× per jaar / €/m²/jaar',
            'effect_tekst' => '0,3 m³ waterberging per m²',
            'technisch' => 'Oppervlakte minimaal 10–15% van afgekoppeld oppervlak',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.3, 'max_m3' => 0.3],
            'min_oppervlak_pct_verhard' => ['min' => 0.10, 'max' => 0.15],
        ],
        [
            'id' => 'waterbergende-verharding',
            'naam' => 'Waterabsorberende / waterbergende / doorgroeibare verharding',
            'niveaus' => ['beide'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'm2',
            'investering_min' => 15,
            'investering_max' => 65,
            'investering_tekst' => '€15–65 / m²',
            'onderhoud_jaar' => '€0,20–0,30 / zie frequentie in bron / €/m²/jaar',
            'effect_tekst' => '0,03–0,09 m³ waterberging per m²',
            'technisch' => 'Lage parkeerdruk; weinig zware belasting; rekening houden met grondwaterstand en bodemdoorlatendheid',
            'waterberging' => ['soort' => 'per_m2', 'min_m3' => 0.03, 'max_m3' => 0.09],
        ],
        [
            'id' => 'waterzuinige-kranen',
            'naam' => 'Waterzuinige kranen en douches',
            'niveaus' => ['gebouw'],
            'risicos' => ['droogte'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 3,
            'investering_max' => 300,
            'investering_tekst' => 'Douchekop €20–50; doorstroombegrenzer €5; kraanonderdelen €3–300',
            'onderhoud_jaar' => 'Geen onderhoudskosten / 1× per jaar controle',
            'effect_tekst' => 'Douche 40–70%; kraan 45–75%; elektronische kraan 1–3 l/gebr.',
            'technisch' => 'Bestaande kraan/douche moet geschikt zijn; comfort moet behouden blijven',
            'waterberging' => null,
        ],
        [
            'id' => 'koele-materialen',
            'naam' => 'Koele materialen',
            'niveaus' => ['beide'],
            'risicos' => ['hittestress'],
            'investering_eenheid' => 'm2',
            'investering_min' => 12,
            'investering_max' => 15,
            'investering_tekst' => '€12–15 / m²',
            'onderhoud_jaar' => 'Sterk afhankelijk van toepassing en materiaal - onbekend',
            'effect_tekst' => 'Gevel/dak 0,1–0,9 °C; lichte bestrating tot 1,9 °C luchttemperatuurdaling',
            'technisch' => 'Situatieafhankelijk; risico op weerkaatsing/verblinding en extra stralingsbelasting',
            'waterberging' => null,
            'geen_planner_invoer' => true,
        ],
        [
            'id' => 'passieve-luchtstroom',
            'naam' => 'Passieve luchtstroom door gebouw mogelijk maken',
            'niveaus' => ['gebouw'],
            'risicos' => ['hittestress'],
            'investering_eenheid' => 'm2',
            'investering_min' => 75,
            'investering_max' => 125,
            'investering_tekst' => '€75-125 / m²',
            'onderhoud_jaar' => 'Geen onderhoudskosten; 1× per jaar controle/reiniging',
            'effect_tekst' => '1,0-3,0 °C gevoelstemperatuur daling',
            'technisch' => 'Ventilatieroosters zijn minder effectief op een hete zomerdag.',
            'waterberging' => null,
            'geen_planner_invoer' => true,
        ],
        [
            'id' => 'buitenzonwering',
            'naam' => 'Buitenzonwering',
            'niveaus' => ['gebouw'],
            'risicos' => ['hittestress'],
            'investering_eenheid' => 'm2',
            'investering_min' => 100,
            'investering_max' => 400,
            'investering_tekst' => '€100-400 / m²',
            'onderhoud_jaar' => '€0-175; 1× per jaar controle/reiniging',
            'effect_tekst' => '2,0-5,0 °C gevoelstemperatuur daling',
            'technisch' => 'De zonwering is het effectiefst op ramen aan de oost-, zuid- en westgevels.',
            'waterberging' => null,
        ],
        [
            'id' => 'grijswater-recycling',
            'naam' => 'Grijswater recycling',
            'niveaus' => ['gebouw'],
            'risicos' => ['droogte'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 6670,
            'investering_max' => 6670,
            'investering_tekst' => 'MBR-grijswatersysteem: €6.670 / stuk',
            'onderhoud_jaar' => '€50; 1× per jaar controle/reiniging',
            'effect_tekst' => '48 liter waterbesparing per persoon per dag',
            'technisch' => 'MBR-grijswatersysteem kost extra ruimte door zuiveringsvat en een opslagvat. Kan niet worden toegepast op collectief wijkniveau, wel bij gestapelde woningbouw of individueel.',
            'waterberging' => null,
        ],
        [
            'id' => 'isolatie',
            'naam' => 'Isolatie van muren, ramen en daken',
            'niveaus' => ['gebouw'],
            'risicos' => ['hittestress'],
            'investering_eenheid' => 'stuk',
            'investering_min' => null,
            'investering_max' => null,
            'investering_tekst' => 'Geen expliciete meerkosten',
            'onderhoud_jaar' => 'Geen onderhoudskosten; geen onderhoud',
            'effect_tekst' => '2-5 keer verlenging thermisch comfort',
            'technisch' => '-',
            'waterberging' => null,
            'geen_planner_invoer' => true,
        ],
        [
            'id' => 'hemelwater-afkoppelen',
            'naam' => 'Hemelwaterafvoer afkoppelen van riolering',
            'niveaus' => ['gebouw'],
            'risicos' => ['wateroverlast'],
            'investering_eenheid' => 'stuk',
            'investering_min' => 0,
            'investering_max' => 0,
            'investering_tekst' => 'Geen sprake van investeringskosten / stuk',
            'onderhoud_jaar' => '€75-150; 1× per jaar controle/reiniging',
            'effect_tekst' => 'Effect is niet meetbaar. Leidt hemelwater af naar andere waterbergingsmaatregelen en draagt zelf niet bij aan opvang of infiltratie.',
            'technisch' => 'Er moeten extra maatregelen getroffen worden om het regenwater op te vangen.',
            'waterberging' => null,
            'geen_planner_invoer' => true,
        ],
    ],
];
